[project]
name = "shinyapps-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "shiny>=1.1.0",
]

[tool.uv]
dev-dependencies = [
    "rsconnect-python>=1.24.0",
]
